version: "3"

services:
  foodie_api_container:
    build:
      context: .
    container_name: foodie_api_backend
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - foodie_net
    depends_on:
      - foodie_db
      - foodie_mongo

  foodie_db:
    image: wallghost/sql-server-dbs:latest
    ports:
      - "1433:1433"
    restart: always
    environment:
      - MSSQL_SA_PASSWORD=123456QWERT@#
    networks:
      - foodie_net

  foodie_mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: "always"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=foodie
      - MONGO_INITDB_ROOT_PASSWORD=foodieMongo123!
    networks:
      - foodie_net
    depends_on:
      - foodie_db
networks:
  foodie_net:
    driver: bridge
