name: foodie-api-backend
on:
  workflow_run: 
    workflows: ["foodie-api-test"]
    branches: [ develop, stage, main]
    types:
      - completed
    
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to Main branch   
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: wallghost/foodie-api-backend
      
      - name: Setting Up .NET CORE 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Installing Project Dependencies
        run: dotnet build --no-restore ./Src/FoodieAPI.Web/