name: foodie-api-test
on:
  push:
    branches:
      - develop
      - stage
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to Main branch
        uses: actions/checkout@v4

      - name: Setting Up .NET CORE 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Clean project
        run: dotnet clean

      - name: Restore dependencies
        run: dotnet restore

      - name: Installing Project Dependencies
        run: dotnet build

      - name: Running Project xUnit Tests
        run: dotnet test Src/FoodieAPI.Tests/FoodieAPI.Tests.csproj --no-build  --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./Src/FoodieAPI.Tests/coverage
#      - name: Code Coverage Report
#        uses: irongut/CodeCoverageSummary@v1.3.0
#        with:
#          filename: ./Src/FoodieAPI.Tests/coverage/**/coverage.cobertura.xml
#          badge: true
#          fail_below_min: true
#          format: markdown
#          hide_branch_rate: false
#          hide_complexity: true
#          indicators: true
#          output: both
#          thresholds: '50 80'
#
#      - name: Add Coverage PR Comment
#        uses: marocchino/sticky-pull-request-comment@v2
#        if: github.event_name == 'pull_request'
#        with:
#          recreate: true
#          path: code-coverage-results.md
